export const invoiceDomainFoundation = {
  name: 'Invoice Domain',
  status: 'foundation-ready',
} as const;

export type InvoiceDomainFoundation = typeof invoiceDomainFoundation;

export const financialCalculationPolicy =
  'Floating-point currency calculations are prohibited. Money and invoice calculation design is deferred.' as const;

export type { Brand } from './brand';
export {
  assertCurrencyCode,
  assertCurrencyDefinition,
  createCurrencyDefinition,
  DEFAULT_CURRENCY_CODE,
  isCurrencyMinorUnitDigits,
  isCurrencyCode,
  parseCurrencyCode,
  parseCurrencyDefinition,
  USD_CURRENCY_DEFINITION,
  type CurrencyCode,
  type CurrencyDefinition,
  type CurrencyMinorUnitDigits,
} from './currency';
export {
  assertIsoDate,
  assertUtcTimestamp,
  isIsoDate,
  isUtcTimestamp,
  parseIsoDate,
  parseUtcTimestamp,
  type IsoDateString,
  type UtcTimestampString,
} from './dates';
export {
  assertBusinessId,
  assertCatalogItemId,
  assertCustomerId,
  assertDocumentId,
  assertInvoiceEventId,
  assertInvoiceId,
  assertInvoiceLineItemId,
  assertPaymentId,
  assertUserId,
  isBusinessId,
  isCatalogItemId,
  isCustomerId,
  isDocumentId,
  isInvoiceEventId,
  isInvoiceId,
  isInvoiceLineItemId,
  isPaymentId,
  isUserId,
  parseBusinessId,
  parseCatalogItemId,
  parseCustomerId,
  parseDocumentId,
  parseInvoiceEventId,
  parseInvoiceId,
  parseInvoiceLineItemId,
  parsePaymentId,
  parseUserId,
  type BusinessId,
  type CatalogItemId,
  type CustomerId,
  type DocumentId,
  type InvoiceEventId,
  type InvoiceId,
  type InvoiceLineItemId,
  type PaymentId,
  type UserId,
} from './identifiers';
export {
  assertInvoiceStatus,
  invoiceStatuses,
  isInvoiceStatus,
  parseInvoiceStatus,
  type InvoiceStatus,
} from './invoice-status';
export {
  assertInvoiceNumber,
  isInvoiceNumber,
  parseInvoiceNumber,
  type InvoiceNumber,
} from './invoice-number';
export {
  addMoney,
  assertMoney,
  assertMonetaryInteger,
  compareMoney,
  createMoney,
  equalMoney,
  isMonetaryInteger,
  MAX_MONETARY_MINOR_UNITS,
  MIN_MONETARY_MINOR_UNITS,
  multiplyMoneyByQuantity,
  negateMoney,
  parseMoneyFromDecimal,
  parseMonetaryInteger,
  parseSerializedMoney,
  serializeMoney,
  subtractMoney,
  type MonetaryInteger,
  type Money,
  type SerializedMoney,
} from './money';
export {
  assertQuantity,
  assertQuantityInteger,
  compareQuantity,
  createQuantity,
  equalQuantity,
  isQuantityInteger,
  MAX_QUANTITY_UNITS,
  MIN_QUANTITY_UNITS,
  parseQuantity,
  parseQuantityInteger,
  parseSerializedQuantity,
  QUANTITY_SCALE,
  QUANTITY_SCALE_FACTOR,
  serializeQuantity,
  type Quantity,
  type QuantityInteger,
  type SerializedQuantity,
} from './quantity';
export {
  DomainValidationError,
  err,
  makeDomainError,
  ok,
  type DomainError,
  type DomainErrorCode,
  type DomainResult,
} from './result';
export {
  applyRateToMoney,
  assertRate,
  assertRateUnits,
  assertSerializedRate,
  createRate,
  isRateUnits,
  MAX_RATE_UNITS,
  MIN_RATE_UNITS,
  parseRateFromDecimalPercent,
  parseRateUnits,
  parseSerializedRate,
  RATE_SCALE,
  serializeRate,
  type Rate,
  type RateUnits,
  type SerializedRate,
} from './rate';
export {
  assertRoundingMode,
  DEFAULT_ROUNDING_MODE,
  isRoundingMode,
  parseRoundingMode,
  roundingModes,
  type RoundingMode,
} from './rounding';
