version = 0.1

[default.global.parameters]
region = "REPLACE_WITH_AWS_REGION"

[default.build.parameters]
template_file = "infra/sam/template.yaml"

[default.deploy.parameters]
stack_name = "unified-invoice-dev"
resolve_s3 = true
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentName=dev"
